### ISSUE TITLE
no memory function export?

### ISSUE THREAD

**Issue by 625673575** [khindemit/unity-wrapper-vorbis#3]
Im currently work on a file format creation, it need to load from memory rather than the ogg file.

**Comment by khindemit** [comment]
Hello! 
Unfortunately in the current implementation there is no supported functions to decode the ogg from memory stream and also encode to memory stream.

We have two options here:
1. Currently I don't have enough time to implement it, but in the future, I'll implement the functionality.
2. If it is urgent for you, you can implement these two functions yourself and create a pull request. Please follow the code style I have already in the project. And add a test functionality to the Unity project here: https://github.com/khindemit/unity-project-vorbis

Best regards
Konstantin

**Comment by khindemit** [comment]
Hey @625673575, I added the missing functions for serializing/deserializing to/from bytes array. Please review the latest release 0.2.0 https://github.com/khindemit/unity-wrapper-vorbis/releases/tag/0.2.0
