### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by Saraistupid** [khindemit/unity-wrapper-vorbis#4]
Hello! Is Linux support planned for this plugin? It would be really great, it shouldn't be much effort since libvorbis is already on Linux

**Comment by khindemit** [comment]
Hi @Saraistupid!

Thank you for your question.
Currently I don't have Linux machine to build and test the plugin. I can spend some time on building the plugin under Windows for Linux. Then I can provide the libraries to you and you can test it. Is it an option for you?

**Comment by Saraistupid** [comment]
> Hi @Saraistupid!
> 
> Thank you for your question. Currently I don't have Linux machine to build and test the plugin. I can spend some time on building the plugin under Windows for Linux. Then I can provide the libraries to you and you can test it. Is it an option for you?

Yeah that's fine!

**Comment by Saraistupid** [comment]
Hey! Any progress?

**Comment by minecraftfromsans** [comment]
I could help with the testing too.

**Comment by Saraistupid** [comment]
Alright! It's fine, I can wait

**Comment by khindemit** [comment]
Hey guys, I tried to build the plugin yesterday in Visual Studio with CMake Linux build target. It connects to remote Ubuntu and tries to build on that machine. I have a virtual server with Ubuntu, I tried to use the server to build the plugin. But there was problems with installing Ninja. It could not be installed because of "sa-compile error".
I'll try in the next days, to install a local Ubuntu extension on my windows machine and build with it. I'll keep you updated. Sorry for the delay.

**Comment by Saraistupid** [comment]
it's fine! visual studio can be a bitch sometimes with linux applications

**Comment by khindemit** [comment]
Hey guys (@Saraistupid and @minecraftfromsans ), sorry for the delay. I had a lot of work.
Here are the release and debug builds made by Visual Studio 2022 connected to local Ubuntu 20.04.4 LTS on Win 10. The build system CMake + Ninja.

I can not test the libraries in Unity editor. Can you please do it for me. Please run the runtime tests and make sure all tests pass in Unity editor under Linux.
You can use the release version of the library. But if there are crashes, you can replace it with debug build and look in the editor logs after crash is reproduced.

Once you confirm that the libraries work, I'll make a release here. Thanks for the support!

[libVorbisPlugin.zip Release build](https://github.com/khindemit/unity-wrapper-vorbis/files/8405005/libVorbisPlugin.zip)
[libVorbisPlugin.zip Debug build](https://github.com/khindemit/unity-wrapper-vorbis/files/8405008/libVorbisPlugin.zip)

**Comment by Saraistupid** [comment]
Hello! it's fine, the wait is worth it, one issue though, how do I install it? I assume I can just make a directory called `Linux` inside `VorbisPlugin/Plugins/` and put the .so file inside it?

**Comment by khindemit** [comment]
Hey @Saraistupid,

yes, put the library file in the Plugins folder inside of Linux directory. After the library is imported make sure to check the import settings for correctness:
Only the Linux x64 should be enabled for the library.

Good luck!

**Comment by Saraistupid** [comment]
Works under the editor only, I tried the release build only
When running it in a build it just errors
I disabled every platform other than Linux x64 and Editor, which I assume you meant by " Only the Linux x64 should be enabled for the library."
Is there anything else I have to do on my end? I can also provide logs from the debug build of libvorbis but I'll have to do it later
```
(process:17864): Gtk-WARNING **: 01:03:42.776: Locale not supported by C library.
	Using the fallback 'C' locale.
Fallback handler could not load library /home/e404nnf/Desktop/HSVRBTEST/HS_Data/Mono/libVorbisPlugin
Fallback handler could not load library /home/e404nnf/Desktop/HSVRBTEST/HS_Data/Mono/libVorbisPlugin.so
Fallback handler could not load library /home/e404nnf/Desktop/HSVRBTEST/HS_Data/Mono/VorbisPlugin
Fallback handler could not load library /home/e404nnf/Desktop/HSVRBTEST/HS_Data/Mono/libVorbisPlugin
Fallback handler could not load library /home/e404nnf/Desktop/HSVRBTEST/HS_Data/Mono/libVorbisPlugin.so
Fallback handler could not load library /home/e404nnf/Desktop/HSVRBTEST/HS_Data/Mono/libVorbisPlugin
Fallback handler could not load library /home/e404nnf/Desktop/HSVRBTEST/HS_Data/Mono/libVorbisPlugin
Fallback handler could not load library /home/e404nnf/Desktop/HSVRBTEST/HS_Data/Mono/libVorbisPlugin.so
Fallback handler could not load library /home/e404nnf/Desktop/HSVRBTEST/HS_Data/Mono/VorbisPlugin
Fallback handler could not load library /home/e404nnf/Desktop/HSVRBTEST/HS_Data/Mono/libVorbisPlugin
Fallback handler could not load library /home/e404nnf/Desktop/HSVRBTEST/HS_Data/Mono/libVorbisPlugin.so
Fallback handler could not load library /home/e404nnf/Desktop/HSVRBTEST/HS_Data/Mono/libVorbisPlugin
Fallback handler could not load library /home/e404nnf/Desktop/HSVRBTEST/HS_Data/Mono/libVorbisPlugin
Fallback handler could not load library /home/e404nnf/Desktop/HSVRBTEST/HS_Data/Mono/libVorbisPlugin.so
Fallback handler could not load library /home/e404nnf/Desktop/HSVRBTEST/HS_Data/Mono/VorbisPlugin
Fallback handler could not load library /home/e404nnf/Desktop/HSVRBTEST/HS_Data/Mono/libVorbisPlugin
Fallback handler could not load library /home/e404nnf/Desktop/HSVRBTEST/HS_Data/Mono/libVorbisPlugin.so
Fallback handler could not load library /home/e404nnf/Desktop/HSVRBTEST/HS_Data/Mono/libVorbisPlugin
Fallback handler could not load library /home/e404nnf/Desktop/HSVRBTEST/HS_Data/Mono/libVorbisPlugin
Fallback handler could not load library /home/e404nnf/Desktop/HSVRBTEST/HS_Data/Mono/libVorbisPlugin.so
Fallback handler could not load library /home/e404nnf/Desktop/HSVRBTEST/HS_Data/Mono/VorbisPlugin
Fallback handler could not load library /home/e404nnf/Desktop/HSVRBTEST/HS_Data/Mono/libVorbisPlugin
Fallback handler could not load library /home/e404nnf/Desktop/HSVRBTEST/HS_Data/Mono/libVorbisPlugin.so
Fallback handler could not load library /home/e404nnf/Desktop/HSVRBTEST/HS_Data/Mono/libVorbisPlugin
DllNotFoundException: VorbisPlugin
  at (wrapper managed-to-native) OggVorbis.NativeBridge.FreeSamplesArrayNativeMemory(intptr&)
  at OggVorbis.VorbisPlugin.ToAudioClip (System.Byte[] bytes, System.String audioClipName, System.Int32 maxSamplesToRead) [0x0008d] in <9720260cdc3844858c345ffa404eb0a0>:0 
  at HeavenStudio.Editor.Editor.<OpenRemix>b__41_0 (System.String[] paths) [0x000e4] in <ad04f3fbaaa34fdebc5eb447d947b9a0>:0 
  at SFB.StandaloneFileBrowserLinux+<>c.<OpenFilePanelAsync>b__13_0 (System.String result) [0x00016] in <1d35019f4cef4456ba28726eb92b41bc>:0 
  at (wrapper managed-to-native) SFB.StandaloneFileBrowserLinux.DialogOpenFilePanelAsync(string,string,string,bool,SFB.StandaloneFileBrowserLinux/AsyncCallback)
  at SFB.StandaloneFileBrowserLinux.OpenFilePanelAsync (System.String title, System.String directory, SFB.ExtensionFilter[] extensions, System.Boolean multiselect, System.Action`1[T] cb) [0x0000f] in <1d35019f4cef4456ba28726eb92b41bc>:0 
  at SFB.StandaloneFileBrowser.OpenFilePanelAsync (System.String title, System.String directory, SFB.ExtensionFilter[] extensions, System.Boolean multiselect, System.Action`1[T] cb) [0x00000] in <1d35019f4cef4456ba28726eb92b41bc>:0 
  at HeavenStudio.Editor.Editor.OpenRemix () [0x0002e] in <ad04f3fbaaa34fdebc5eb447d947b9a0>:0 
  at UnityEngine.Events.InvokableCall.Invoke () [0x00010] in <a83e096d0ba5413da59ce235b648c30c>:0 
  at UnityEngine.Events.UnityEvent.Invoke () [0x00022] in <a83e096d0ba5413da59ce235b648c30c>:0 
  at UnityEngine.UI.Button.Press () [0x0001c] in <be4159b5a4d04fc28ebe81c26b1ca772>:0 
  at UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) [0x00009] in <be4159b5a4d04fc28ebe81c26b1ca772>:0 
  at UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) [0x00007] in <be4159b5a4d04fc28ebe81c26b1ca772>:0 
  at UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) [0x0006c] in <be4159b5a4d04fc28ebe81c26b1ca772>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData, GameObject)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent()
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()

**Comment by Saraistupid** [comment]
I just checked the import settings for Windows x64 and copy it like you suggested, it still didn't work, but when I set the CPU to "Any CPU" it worked (I had it set to x86_64 before) which is a little weird I guess, but it works.
![image](https://user-images.githubusercontent.com/37207067/162179022-0928c839-d1bd-4bc1-8d89-f597be97470b.png)

**Comment by khindemit** [comment]
Hey @Saraistupid,

thanks for update. I am not aware how the equivalent of Standalone (Windows Player build) is name in the Unity running under Linux. Probably it is also "Standalone", probably some other name. My point was: you need to enable the library usage for editor and player build for Linux.
Actually the library is build for the x64 abi. I can try to build also for x86 if you need.

**Comment by Saraistupid** [comment]
Linux and Mac and Windows use the same name under Unity, it's "Standalone", and yes I am aware it is an x64 library but it didn't load when I set the "CPU" option in import settings to x86_64, only with "Any CPU option"

**Comment by khindemit** [comment]
Do you need the x86 build?
Have you tried to run the runtime tests?

**Comment by Saraistupid** [comment]
> Do you need the x86 build? 

I don't think anyone uses x86 nowadays, so not really.

**Comment by khindemit** [comment]
Hey @Saraistupid,

Can you please share with me the metafile for the library?
So that I can put it into project and make a new release.

Best regards
Konstantin

**Comment by Saraistupid** [comment]
Hello! Sorry I got busy with school 
Here's the metafile of `libVorbisPlugin.so` : https://cdn.discordapp.com/attachments/862760859318485032/962887452580778014/libVorbisPlugin.so.meta
